### ISSUE TITLE
Issues about Cardiac bSSFP-LGE datasets

### ISSUE THREAD

**Issue by Kaiseem** [cheng-01037/Causality-Medical-Image-Domain-Generalization#1]
Firstly, i want to thank your Great work to the community! Your team really done a good job for researchers to follow.

Secondly, could you provide the preprocessing pipeline for the Cardiac bSSFP-LGE datasets? Since i noticed the complex pipeline in the abdominal dataset and i'm afraid my own preprocessing is not the same as yours, thus making the results uncomparable.

**Comment by rahulv54** [comment]
Any updates?

**Comment by Kaiseem** [comment]
sadly nope ^_^

**Comment by cheng-01037** [comment]
Will update with you once it's ready. Sorry that I am quite busy these days. Please stay tuned.
