### ISSUE TITLE
Data split for upper bound

### ISSUE THREAD

**Issue by alexbgl** [cheng-01037/Causality-Medical-Image-Domain-Generalization#2]
Hi @cheng-01037,
thanks for sharing the code of your interesting work.

In your paper, you state that "for the target domain(s), we used all the images for testing". How did you split the data to train and test the 'upper bound' model. Is the upper bound model only evaluated on the test split? Or do you perform cross-validation?

Another question I have concerns the 'ERM' baseline. Does this mean plain training on a single source domain without any adaptation / generalization methods? Or what exactly does this baseline do?

Thanks!

**Comment by cheng-01037** [comment]
Yes. They are evaluated on the test fold (so the numbers are not directly comparable). ERM means standard ERM on conventional fully supervised setting, with standard photometric + geometric transformations for data augmentation.
